New notifier - GitHub Issues
GoogleCloudPlatform/cloud-build-notifiers pull request #141
Opened 2022-07-01 03:06 UTC by glasnt

b/229753500

<img width="922" alt="Preview of New GitHub Issues Notifier" src="https://user-images.githubusercontent.com/813732/176815345-42207e55-0dd1-48a0-8d57-c0b46003123c.png">

This notifier creates an issue against the configured GitHub repo. It also uses the new template feature to allow full customisation of the notification format, including GitHub features like labels and assignees (as shown in the screenshot).

2022-07-08 00:50 UTC, ace-n commented
@prabenzom @Aric1088 hey folks! @glasnt and I were hoping to get this reviewed within the next week or so.

Is that something y'all can arrange? _(Thanks! 🤗 )_

2022-07-12 01:52 UTC, Aric1088 commented on githubissues/githubissues.json
> +}
please add a new line

2022-07-12 01:55 UTC, Aric1088 requested changes
just a few small changes, but LGTM

2022-07-12 01:55 UTC, Aric1088 commented on githubissues/githubissues.yaml.example
> +      uri: gs://project-name/githuissues.json
fix typo

2022-07-12 02:34 UTC, glasnt commented on githubissues/githubissues.json
> +}
Do you mean to the end of this file?

2022-07-12 03:54 UTC, Aric1088 commented on githubissues/githubissues.json
> +}
yep!

2022-07-13 14:55 UTC, merged

2022-07-13 14:55 UTC, Aric1088 reviewed
LGTM